//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace xApp.Entity
{
     [DataContract]
    public partial class Department
    {
        #region Primitive Properties
         [DataMember(Name = "id")]
        public virtual int Id
        {
            get;
            set;
        }
         [DataMember(Name = "name")]
        public virtual string Name
        {
            get;
            set;
        }
         [DataMember(Name = "description")]
        public virtual string Description
        {
            get;
            set;
        }
         [DataMember(Name = "parentId")]
        public virtual int ParentId
        {
            get;
            set;
        }

        #endregion
    }
}
