//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace xApp.Entity
{
     [DataContract]
    public partial class Menu
    {
        #region Primitive Properties
         [DataMember(Name = "id")]
        public virtual int Id
        {
            get;
            set;
        }
         [DataMember(Name = "caption")]
        public virtual string Caption
        {
            get;
            set;
        }
         [DataMember(Name = "description")]
        public virtual string Description
        {
            get;
            set;
        }
         [DataMember(Name = "parentId")]
        public virtual int ParentId
        {
            get;
            set;
        }
         [DataMember(Name = "moduleId")]
        public virtual int ModuleId
        {
            get;
            set;
        }
         [DataMember(Name = "application")]
        public virtual string Application
        {
            get;
            set;
        }
         [DataMember(Name = "orderNO")]
        public virtual int OrderNO
        {
            get;
            set;
        }
         [DataMember(Name = "icon")]
        public virtual string Icon
        {
            get;
            set;
        }

        #endregion
    }
}
