//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace xApp.Web.Models
{
     [DataContract]
    public partial class CategoryItem
    {
        #region Primitive Properties
         [DataMember(Name = "id")]
        public virtual int Id
        {
            get;
            set;
        }
         [DataMember(Name = "code")]
        public virtual string Code
        {
            get;
            set;
        }
         [DataMember(Name = "name")]
        public virtual string Name
        {
            get;
            set;
        }
         [DataMember(Name = "isDefault")]
        public virtual Nullable<bool> IsDefault
        {
            get;
            set;
        }
         [DataMember(Name = "order")]
        public virtual Nullable<short> Order
        {
            get;
            set;
        }
         [DataMember(Name = "categoryId")]
        public virtual Nullable<int> CategoryId
        {
            get;
            set;
        }

        #endregion

    }
}
