//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace xApp.Web.Models
{
    public partial class xAppContext : ObjectContext
    {
        public const string ConnectionString = "name=xAppContext";
        public const string ContainerName = "xAppContext";
    
        #region Constructors
    
        public xAppContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public xAppContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public xAppContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Application> Applications
        {
            get { return _applications  ?? (_applications = CreateObjectSet<Application>("Applications")); }
        }
        private ObjectSet<Application> _applications;
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<CategoryItem> CategoryItems
        {
            get { return _categoryItems  ?? (_categoryItems = CreateObjectSet<CategoryItem>("CategoryItems")); }
        }
        private ObjectSet<CategoryItem> _categoryItems;
    
        public ObjectSet<Department> Departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<Department>("Departments")); }
        }
        private ObjectSet<Department> _departments;
    
        public ObjectSet<Menu> Menus
        {
            get { return _menus  ?? (_menus = CreateObjectSet<Menu>("Menus")); }
        }
        private ObjectSet<Menu> _menus;
    
        public ObjectSet<Module> Modules
        {
            get { return _modules  ?? (_modules = CreateObjectSet<Module>("Modules")); }
        }
        private ObjectSet<Module> _modules;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<Rolemenu> Rolemenus
        {
            get { return _rolemenus  ?? (_rolemenus = CreateObjectSet<Rolemenu>("Rolemenus")); }
        }
        private ObjectSet<Rolemenu> _rolemenus;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<UserDepartment> UserDepartments
        {
            get { return _userDepartments  ?? (_userDepartments = CreateObjectSet<UserDepartment>("UserDepartments")); }
        }
        private ObjectSet<UserDepartment> _userDepartments;
    
        public ObjectSet<UserRole> UserRoles
        {
            get { return _userRoles  ?? (_userRoles = CreateObjectSet<UserRole>("UserRoles")); }
        }
        private ObjectSet<UserRole> _userRoles;

        #endregion

    }
}
